name: Deploy to Server

on:
  push:
    branches:
      - main  # 或者您要监控的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      run: mvn install

    - name: Build backend
      run: mvn package

    - name: Install frontend dependencies
      run: cd src/main/resources/admin/admin && npm install

    - name: Update caniuse-lite
      run: cd src/main/resources/admin/admin && npm update

    - name: Build frontend
      run: cd src/main/resources/admin/admin && npm run build

    - name: Create deployment directory on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p /root/xiaoyuanpaotui/backend
          mkdir -p /root/xiaoyuanpaotui/frontend
          mkdir -p /opt/myapp
          mkdir -p /var/www/html

    - name: Copy backend files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "target/xiaoyuanfuwupingtai-0.0.1-SNAPSHOT.jar"
        target: "/root/xiaoyuanpaotui/backend"

    - name: Copy frontend files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "src/main/resources/admin/admin/dist/*"
        target: "/root/xiaoyuanpaotui/frontend"

    - name: Create systemd service for Spring Boot application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "[Unit]
          Description=Xiaoyuan Fuwupingtai Spring Boot Application
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/bin/java -jar /root/xiaoyuanpaotui/backend/xiaoyuanfuwupingtai-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/xiaoyuanfuwupingtai.service
          sudo systemctl daemon-reload
          sudo systemctl enable xiaoyuanfuwupingtai

    - name: Restart Spring Boot application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo systemctl restart xiaoyuanfuwupingtai
