name: Deploy to Server

on:
  push:
    branches:
      - main  # 或者您要监控的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: mvn install

      - name: Build backend
        run: mvn package

      - name: Install frontend dependencies
        run: cd src/main/resources/admin.admin && npm install

      - name: Build frontend
        run: cd src/main/resources/admin.admin && npm run build

      - name: Create deployment directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /root/xiaoyuanpaotui/backend
            mkdir -p /root/xiaoyuanpaotui/frontend

      - name: Copy backend files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "target/xiaoyuanfuwupingtai-0.0.1-SNAPSHOT.jar"
          target: "/root/xiaoyuanpaotui/backend"

      - name: Copy frontend files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/main/resources/admin.admin/dist/*"
          target: "/root/xiaoyuanpaotui/frontend"

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 进入部署目录
            cd /root/xiaoyuanpaotui
            
            # 停止旧服务
            sudo systemctl stop myapp
            
            # 部署后端新版本
            cp backend/xiaoyuanfuwupingtai-0.0.1-SNAPSHOT.jar /opt/myapp/
            
            # 部署前端新版本
            cp -r frontend/* /var/www/html/
            
            # 启动新服务
            sudo systemctl start myapp
